### ISSUE TITLE
Check the assignment

### ISSUE THREAD

**Issue by AlekseiILitvinov** [AlekseiILitvinov/Week1HomeworkWallpapers#1]
The assignment was to write a program, which calculates the needed amount of wallpaper rolls given the room's dimensions.
_There is a known design flaw - the pattern shift doesn't calculate the possible backwards shift of the wallpaper strip, thus possibly leading to overestimation of the needed number of rolls for some of the more complicated cases. Clarification of the desired logic may be needed._

**Comment by coursar** [comment]
Пофиксить: #2, #3
