### ISSUE TITLE
Объявляйте переменные ближе к месту использования

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/Week1HomeworkWallpapers#5]
https://github.com/AlekseiILitvinov/Week1HomeworkWallpapers/blob/12790a2346bc47d17842d7b3b7334cedb417fb89/src/Main.java#L12-L33

См. issue к задаче расчёта топлива

**Comment by AlekseiILitvinov** [comment]
Fixed - declaring variables immediately before use
